### ISSUE TITLE
Instructions for installing postgres don't work

### ISSUE THREAD

**Issue by mcatanzaro** [endlessm/azafea#104]
The [instructions for installing Postgres](https://github.com/endlessm/azafea/blob/master/docs/source/install.rst#postgresql) have a couple problems. First problem is that the instructions start out using `/var/lib/pgsql/` but then later switch to `/var/lib/postgresql`. Only the first two lines use the `/var/lib/pgsql/` form, so they should probably be switched to `/var/lib/postgresql`.

Then the next step only works when using `sudo docker` rather than podman:

```
$ podman run --env=PGDATA=/var/lib/postgresql/azafea/data/pgdata --env=POSTGRES_PASSWORD=S3cretPgAdminP@ssw0rd --publish=5432:5432 --volume=/var/lib/postgresql/azafea/data:/var/lib/postgresql/azafea/data:rw postgres:latest
mkdir: cannot create directory ‘/var/lib/postgresql/azafea/data/pgdata’: Permission denied
```

At this point in the instructions, `/var/lib/postgresql/azafea/data` already exists and is owned by root, but /var/lib/postgresql/azafea/data/pgdata` does not exist. If I create that directory too, then the podman command fails with:

```
chmod: changing permissions of '/var/lib/postgresql/azafea/data/pgdata': Permission denied
```

At this point, I'm wondering which user is supposed to own which directories here. I understand that the next step in the installation instructions has me creating an azafea user inside the container, but no such user exists on the host system, and if I were to create that user on the host, then the uids would not match anyway. Probably this is an easy problem, but I'm a stupid desktop developer and don't know anything.

**Comment by adarnimrod** [comment]
@mcatanzaro you can take a look at #108. I think it should work for you now.

**Comment by mcatanzaro** [comment]
Thanks. I'll check this soon.

**Comment by mcatanzaro** [comment]
Confirmed fixed, thanks!
