### ISSUE TITLE
Docker image does not use config generated by entrypoint

### ISSUE THREAD

**Issue by dbnicholson** [endlessm/azafea#188]
In the current code, the [`entrypoint`](https://github.com/endlessm/azafea/blob/master/entrypoint) script templates `config.toml.j2` to `/tmp/config.toml` from environment variables. However, the full [`ENTRYPOINT`](https://github.com/endlessm/azafea/blob/master/Dockerfile#L35) command does not instruct azafea to use it and instead it tries to read the configuration from `/etc/azafea/config.toml` unless you specify the command at runtime as `-c /tmp/config.toml ...`.

The fix would be simple - add `-c /tmp/config.toml` to the `ENTRYPOINT` array. However, that's at odds with the [running documentation](https://azafea.readthedocs.io/en/latest/install.html#running). That says you should bind mount `/etc/azafea` from the host with the expectation that azafea will use `/etc/azafea/config.toml`. If the `ENTRYPOINT` command is changed to use `-c /tmp/config.toml`, that usage would break.

I think the options are:

1. Make the change to have the image use `/tmp/config.toml` and update the documentation to pass the configuration as environment variables. This is how the postgres image (and many others in the Docker world) are handled.
2. Drop the custom entrypoint script and assume the configuration has been been added to the container at `/etc/azafea/config.toml` like the documentation says.

I prefer 1 as it fits better with container orchestration software. The reason this came up is that someone is trying to use azafea on AWS ECS and it can't really work out of the box without some customization. In either case you can always build an image with a custom entrypoint to handle the configuration in the way you prefer. That's what we do at Endless and why we don't run into this problem.

**Comment by wjt** [comment]
What happens if you pass `-c` more than once? Does the last one win? If so I don't see a downside to option 1.

**Comment by dbnicholson** [comment]
Yes it does. The CLI handling makes this a little awkward since `-c` has to be passed before the subcommand. I.e., `pipenv run azafea -c /foo.toml run` works, but `pipenv run azafea run -c /foo.toml` doesn't. So, when running the container you have to pass it first like `docker run -v $PWD/foo.toml:/foo.toml azafea:latest -c /foo.toml run`. Not to mention that the wrappers (`entrypoint` and `pipenv run`) make the `ENTRYPOINT` and `CMD` handling awkward (azafea-metrics-proxy has them arranged slightly differently), but that's a different story.

**Comment by adarnimrod** [comment]
IIRC, I was more in favor of environment variables and the developer (I don't remember who it was at the time) preferred the config file, so we ended up with this neither this nor that status. That is why the CI workflow [overrides the container entrypoint](https://github.com/endlessm/azafea/blob/master/.github/workflows/tests.yml#L41) as that is how he ran the tests locally.
Something else to take in to account is that the config template expects a Redis password. I don't know what would happen if you don't pass the `REDIS_PASSWORD` environment variable.
