### ISSUE TITLE
Optimize some queries

### ISSUE THREAD

**Issue by bochecha** [endlessm/azafea#21]
Here is a dump of queries I've been asked to run on activation/ping data.

Real-world queries provide good insight into what should be optimized and how (adding indexes, splitting columns, adding pre-processed tables, …)

Let's make good use of PostgreSQL's `EXPLAIN` on those!

---

*   Countries with the most new OEM activations over the past 365 days:
```
SELECT count(id) AS count, country
  FROM activation_v1
  WHERE image LIKE 'eosoem-%'
    AND created_at >= NOW() - INTERVAL '365 DAYS'
  GROUP BY country
  ORDER BY count DESC
  LIMIT 10;
```

*   Countries with the most active OEM installations over the past 365 days, limited to machines which have sent 8 pings or more:
```
SELECT count(ping_v1.id) AS count, ping_v1.country
  FROM ping_v1
  JOIN ping_configuration_v1 ON ping_v1.config_id = ping_configuration_v1.id
  WHERE ping_configuration_v1.image LIKE 'eosoem-%'
    AND ping_v1.count >= 8
    AND ping_v1.created_at >= NOW() - INTERVAL '365 DAYS'
  GROUP BY ping_v1.country
  ORDER BY count DESC
  LIMIT 10;
```

**Comment by liZe** [comment]
> * Countries with the most new OEM activations over the past 365 days:

Adding an index on `image` greatly improves speed.

> * Countries with the most active OEM installations over the past 365 days, limited to machines which have sent 8 pings or more:

Unfortunately, this one is difficult to optimize. Most of the time is spent filtering the pings count, and there’s already an index on `created_at`. Without an extra table, there’s probably nothing we can do. The request is fast enough (less than 15 seconds), I think that we don’t need a new table for that.

**Comment by wjt** [comment]
I think that first query was written before we split the fields of `image` out into `image_product` etc. If we wrote that query today we would use `WHERE image_product = 'eosoem'`. Is there an appropriate index there?

**Comment by liZe** [comment]
> I think that first query was written before we split the fields of `image` out into `image_product` etc. If we wrote that query today we would use `WHERE image_product = 'eosoem'`. Is there an appropriate index there?

There’s an index, you’re right, there’s no need to add an index on `image`.

We can then safely close this issue, can’t we?

**Comment by wjt** [comment]
Sounds like it!
